spring.application.name=resource-entitlement-engine
server.port=8080
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/entitlements}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
